// Code generated by MockGen. DO NOT EDIT.
// Source: fulfillments.go

// Package mockshopify is a generated GoMock package.
package mockshopify

import (
	reflect "reflect"

	shopify "github.com/MOHC-LTD/shopify/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockFulfillmentRepository is a mock of FulfillmentRepository interface.
type MockFulfillmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFulfillmentRepositoryMockRecorder
}

// MockFulfillmentRepositoryMockRecorder is the mock recorder for MockFulfillmentRepository.
type MockFulfillmentRepositoryMockRecorder struct {
	mock *MockFulfillmentRepository
}

// NewMockFulfillmentRepository creates a new mock instance.
func NewMockFulfillmentRepository(ctrl *gomock.Controller) *MockFulfillmentRepository {
	mock := &MockFulfillmentRepository{ctrl: ctrl}
	mock.recorder = &MockFulfillmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFulfillmentRepository) EXPECT() *MockFulfillmentRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockFulfillmentRepository) Cancel(fulfillmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", fulfillmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockFulfillmentRepositoryMockRecorder) Cancel(fulfillmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockFulfillmentRepository)(nil).Cancel), fulfillmentID)
}

// Create mocks base method.
func (m *MockFulfillmentRepository) Create(fulfillment shopify.Fulfillment) (shopify.Fulfillment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", fulfillment)
	ret0, _ := ret[0].(shopify.Fulfillment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFulfillmentRepositoryMockRecorder) Create(fulfillment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFulfillmentRepository)(nil).Create), fulfillment)
}

// UpdateTracking mocks base method.
func (m *MockFulfillmentRepository) UpdateTracking(fulfillment shopify.Fulfillment) (shopify.Fulfillment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTracking", fulfillment)
	ret0, _ := ret[0].(shopify.Fulfillment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTracking indicates an expected call of UpdateTracking.
func (mr *MockFulfillmentRepositoryMockRecorder) UpdateTracking(fulfillment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTracking", reflect.TypeOf((*MockFulfillmentRepository)(nil).UpdateTracking), fulfillment)
}
