// Code generated by MockGen. DO NOT EDIT.
// Source: fulfillment-orders.go

// Package mockshopify is a generated GoMock package.
package mockshopify

import (
	reflect "reflect"

	shopify "github.com/MOHC-LTD/shopify"
	gomock "github.com/golang/mock/gomock"
)

// MockFulfillmentOrderRepository is a mock of FulfillmentOrderRepository interface.
type MockFulfillmentOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFulfillmentOrderRepositoryMockRecorder
}

// MockFulfillmentOrderRepositoryMockRecorder is the mock recorder for MockFulfillmentOrderRepository.
type MockFulfillmentOrderRepositoryMockRecorder struct {
	mock *MockFulfillmentOrderRepository
}

// NewMockFulfillmentOrderRepository creates a new mock instance.
func NewMockFulfillmentOrderRepository(ctrl *gomock.Controller) *MockFulfillmentOrderRepository {
	mock := &MockFulfillmentOrderRepository{ctrl: ctrl}
	mock.recorder = &MockFulfillmentOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFulfillmentOrderRepository) EXPECT() *MockFulfillmentOrderRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFulfillmentOrderRepository) Get(id int64) (shopify.FulfillmentOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(shopify.FulfillmentOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFulfillmentOrderRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFulfillmentOrderRepository)(nil).Get), id)
}

// List mocks base method.
func (m *MockFulfillmentOrderRepository) List(orderID int64) (shopify.FulfillmentOrders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orderID)
	ret0, _ := ret[0].(shopify.FulfillmentOrders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFulfillmentOrderRepositoryMockRecorder) List(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFulfillmentOrderRepository)(nil).List), orderID)
}
